### PR TITLE
Improve listener

### PR DESCRIPTION
**Pull request by josesimoes**
- Move all declarations to the method start because this speeds up execution.
- Store RawUrl before starting comparing routes because sometimes the request hasn't been completely processed on the first pass and it causes an exception when the request starts to be re-processed on the second pass of the foreach below.

### CODE REVIEW

**Comment by Ellerbach** [comment]
Thanks for those proposed changes. I will not take them now because I've been working on making this part already part of a separated thread and those variables can't be declared outside of this potential thread as it won't work in this case. I'm keeping them in a warm place if it happens that the modification I4m working on are not working correctly.

**Comment by josesimoes** [comment]
OK understood.

One thing that I strongly suggest that you take into your new code is the `rawUrl = context.Request.RawUrl;`.
On scenarios of repeated requests (or fast incoming requests) that's mandatory for the reasons explained. Otherwise there a high likelihood that exceptions are thrown.

For the rest it's OK either way. The impact exists on creating the vars over and over, but it's minimal.

**Comment by Ellerbach** [comment]
> One thing that I strongly suggest that you take into your new code is the `rawUrl = context.Request.RawUrl;`.

yes, will do. I was even thinking in adding to the webargument parameters and split over context.Response and context.Request to be in a more "flat" pattern and avoid what you mention

**Comment by Ellerbach** [comment]
I think I implemented all in the new server commit. I will close it then.

**Pull request closed without merging**
